services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - db
    volumes:
      - .:/workspace
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      - "8088:3000"
    cmd:
      - npm run build
      - npm run start

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5450:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
